-- CreateEnum
CREATE TYPE "request_status" AS ENUM (
    'new',
    'contacted',
    'quote_sent',
    'confirmed',
    'completed',
    'cancelled'
);

-- Human-friendly request numbers are generated by PostgreSQL so concurrent
-- submissions cannot receive the same code.
CREATE SEQUENCE "request_code_seq"
    AS BIGINT
    START WITH 1042
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

-- CreateTable
CREATE TABLE "product_categories" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
    "name" TEXT NOT NULL,
    "slug" TEXT NOT NULL,
    "description" TEXT,
    "display_order" INTEGER NOT NULL DEFAULT 0,
    "is_active" BOOLEAN NOT NULL DEFAULT true,
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "product_categories_pkey" PRIMARY KEY ("id"),
    CONSTRAINT "product_categories_name_not_blank" CHECK (btrim("name") <> ''),
    CONSTRAINT "product_categories_slug_not_blank" CHECK (btrim("slug") <> ''),
    CONSTRAINT "product_categories_display_order_nonnegative" CHECK ("display_order" >= 0)
);

-- CreateTable
CREATE TABLE "products" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
    "category_id" BIGINT NOT NULL,
    "sku" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "slug" TEXT NOT NULL,
    "short_description" TEXT,
    "description" TEXT,
    "manufacturer" TEXT,
    "model_number" TEXT,
    "specifications" JSONB NOT NULL DEFAULT '{}',
    "is_active" BOOLEAN NOT NULL DEFAULT true,
    "is_featured" BOOLEAN NOT NULL DEFAULT false,
    "display_order" INTEGER NOT NULL DEFAULT 0,
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "products_pkey" PRIMARY KEY ("id"),
    CONSTRAINT "products_sku_not_blank" CHECK (btrim("sku") <> ''),
    CONSTRAINT "products_name_not_blank" CHECK (btrim("name") <> ''),
    CONSTRAINT "products_slug_not_blank" CHECK (btrim("slug") <> ''),
    CONSTRAINT "products_display_order_nonnegative" CHECK ("display_order" >= 0)
);

-- CreateTable
CREATE TABLE "product_images" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
    "product_id" BIGINT NOT NULL,
    "url" TEXT NOT NULL,
    "alt_text" TEXT,
    "display_order" INTEGER NOT NULL DEFAULT 0,
    "is_primary" BOOLEAN NOT NULL DEFAULT false,
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "product_images_pkey" PRIMARY KEY ("id"),
    CONSTRAINT "product_images_url_not_blank" CHECK (btrim("url") <> ''),
    CONSTRAINT "product_images_display_order_nonnegative" CHECK ("display_order" >= 0)
);

-- CreateTable
CREATE TABLE "order_requests" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
    "request_code" TEXT NOT NULL DEFAULT concat('REQ-', nextval('request_code_seq'::regclass)),
    "status" "request_status" NOT NULL DEFAULT 'new',
    "hospital_name" TEXT NOT NULL,
    "contact_person" TEXT NOT NULL,
    "contact_phone" TEXT NOT NULL,
    "contact_email" TEXT,
    "notes" TEXT,
    "assigned_to_user_id" UUID,
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "order_requests_pkey" PRIMARY KEY ("id"),
    CONSTRAINT "order_requests_request_code_format" CHECK ("request_code" ~ '^REQ-[0-9]+$'),
    CONSTRAINT "order_requests_hospital_name_not_blank" CHECK (btrim("hospital_name") <> ''),
    CONSTRAINT "order_requests_contact_person_not_blank" CHECK (btrim("contact_person") <> ''),
    CONSTRAINT "order_requests_contact_phone_not_blank" CHECK (btrim("contact_phone") <> '')
);

-- The staff UUID columns intentionally do not reference auth.users. Supabase
-- manages that schema independently, while these UUIDs still preserve an audit trail.

-- CreateTable
CREATE TABLE "order_request_items" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
    "request_id" BIGINT NOT NULL,
    "product_id" BIGINT,
    "product_sku" TEXT NOT NULL,
    "product_name" TEXT NOT NULL,
    "quantity" INTEGER NOT NULL,
    "notes" TEXT,
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "order_request_items_pkey" PRIMARY KEY ("id"),
    CONSTRAINT "order_request_items_product_sku_not_blank" CHECK (btrim("product_sku") <> ''),
    CONSTRAINT "order_request_items_product_name_not_blank" CHECK (btrim("product_name") <> ''),
    CONSTRAINT "order_request_items_quantity_positive" CHECK ("quantity" > 0)
);

-- CreateTable
CREATE TABLE "request_status_history" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
    "request_id" BIGINT NOT NULL,
    "from_status" "request_status",
    "to_status" "request_status" NOT NULL,
    "note" TEXT,
    "changed_by_user_id" UUID,
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "request_status_history_pkey" PRIMARY KEY ("id"),
    CONSTRAINT "request_status_history_is_change" CHECK ("from_status" IS NULL OR "from_status" <> "to_status")
);

-- CreateIndex
CREATE UNIQUE INDEX "product_categories_name_key" ON "product_categories"("name");
CREATE UNIQUE INDEX "product_categories_slug_key" ON "product_categories"("slug");
CREATE INDEX "product_categories_active_order_idx" ON "product_categories"("is_active", "display_order");

CREATE UNIQUE INDEX "products_sku_key" ON "products"("sku");
CREATE UNIQUE INDEX "products_slug_key" ON "products"("slug");
CREATE INDEX "products_category_active_order_idx" ON "products"("category_id", "is_active", "display_order");
CREATE INDEX "products_active_order_idx" ON "products"("is_active", "display_order");
CREATE INDEX "products_featured_active_order_idx" ON "products"("is_featured", "is_active", "display_order");

CREATE UNIQUE INDEX "product_images_product_order_key" ON "product_images"("product_id", "display_order");
CREATE INDEX "product_images_product_primary_idx" ON "product_images"("product_id", "is_primary");
CREATE UNIQUE INDEX "product_images_one_primary_per_product_idx" ON "product_images"("product_id") WHERE "is_primary";

CREATE UNIQUE INDEX "order_requests_request_code_key" ON "order_requests"("request_code");
CREATE INDEX "order_requests_status_created_at_idx" ON "order_requests"("status", "created_at" DESC);
CREATE INDEX "order_requests_created_at_idx" ON "order_requests"("created_at" DESC);
CREATE INDEX "order_requests_contact_phone_idx" ON "order_requests"("contact_phone");
CREATE INDEX "order_requests_assignee_status_idx" ON "order_requests"("assigned_to_user_id", "status");

CREATE UNIQUE INDEX "order_request_items_request_product_key" ON "order_request_items"("request_id", "product_id");
CREATE INDEX "order_request_items_product_id_idx" ON "order_request_items"("product_id");

CREATE INDEX "request_status_history_request_created_at_idx" ON "request_status_history"("request_id", "created_at");
CREATE INDEX "request_status_history_changed_by_user_id_idx" ON "request_status_history"("changed_by_user_id");

-- AddForeignKey
ALTER TABLE "products"
    ADD CONSTRAINT "products_category_id_fkey"
    FOREIGN KEY ("category_id") REFERENCES "product_categories"("id")
    ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE "product_images"
    ADD CONSTRAINT "product_images_product_id_fkey"
    FOREIGN KEY ("product_id") REFERENCES "products"("id")
    ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "order_request_items"
    ADD CONSTRAINT "order_request_items_request_id_fkey"
    FOREIGN KEY ("request_id") REFERENCES "order_requests"("id")
    ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "order_request_items"
    ADD CONSTRAINT "order_request_items_product_id_fkey"
    FOREIGN KEY ("product_id") REFERENCES "products"("id")
    ON DELETE SET NULL ON UPDATE CASCADE;

ALTER TABLE "request_status_history"
    ADD CONSTRAINT "request_status_history_request_id_fkey"
    FOREIGN KEY ("request_id") REFERENCES "order_requests"("id")
    ON DELETE CASCADE ON UPDATE CASCADE;

-- Supabase exposes the public schema through its Data API. RLS is enabled on
-- every domain table and no broad anon/authenticated policies are granted;
-- catalog reads, customer submissions, and staff operations go through Nuxt APIs.
ALTER TABLE "product_categories" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "products" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "product_images" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "order_requests" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "order_request_items" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "request_status_history" ENABLE ROW LEVEL SECURITY;

COMMENT ON TABLE "order_requests" IS 'Customer equipment requests submitted for telephone confirmation.';
COMMENT ON COLUMN "order_requests"."request_code" IS 'Human-friendly code customers quote during the confirmation call.';
COMMENT ON COLUMN "order_request_items"."product_sku" IS 'SKU snapshot retained even if the linked product later changes or is deleted.';
COMMENT ON COLUMN "order_request_items"."product_name" IS 'Product-name snapshot retained even if the linked product later changes or is deleted.';
